apiVersion: apps/v1
kind: Deployment
metadata:
    name: db-deployment
    labels:
        app: db
        tier: database
spec:
    replicas: 1
    selector:
        matchLabels:
            app: db
            tier: database
    strategy:
        type: Recreate
    template:
        metadata:
            labels:
                app: db
                tier: database
        spec:
            containers:
                - name: db-deployment
                  image: mysql:latest
                  env:
                      - name: MYSQL_ROOT_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: mysql-secrets
                                key: password
                      - name: MYSQL_DATABASE
                        valueFrom:
                            configMapKeyRef:
                                name: db-config
                                key: dbName
                  ports:
                      - containerPort: 3306
                  volumeMounts:
                      - mountPath: "/var/lib/mysql/"
                        name: db-pv-storage
                      - mountPath: "/docker-entrypoint-initdb.d"
                        name: init-db
            volumes:
                - name: db-pv-storage
                  persistentVolumeClaim:
                      claimName: db-pv-claim
                - name: init-db
                  configMap:
                      name: db-config
